# Generated by Django 4.0.5 on 2022-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='Ignacio Alcaino', max_length=70),
            preserve_default=False,
        ),
    ]
